### ISSUE TITLE
PropunereNumeDomeniu

### ISSUE THREAD

**Issue by GeekGollum** [GeekGollum/0.1#1]

**Comment by opricescu** [comment]
Salut,

Imi cer scuze ca am lungit putin ddl-ul, dar tot au aparut chestii neprevazute si tema gasirii unui nume pe IT s-a dovedit mai grea decat credeam initial in mare parte pentru ca s-au luat cam toate combinatiile posibile.

Dupa multe incercari de a gasi un nume cool care sa va reprezinte, sa spuna cu ce va ocupati si sa nu fie deja luat, am reusit sa compliam o lista de propuneri. 


Propunerile noastre:

Techdep (sau Tecdep)	Site OK. Nume 1 in UK

IT Fixers          Site ro OK. .com e luat dar mort

Tech Fixers Site ro OK. .com e luat dar mort

Nerd Solutions Site ro OK. . com e luat dar face altceva

Nerd Team     Site ro OK. pe.com e luat dar mort.   

Nerd department Site ro OK. pe.com e luat dar nefolosit.   

Nerdep Site .ro  si .com OK


  Daca ai cumva un feel negativ pentru cuvantul nerd, scrie in google: "nerd is" si "nerds are" . Cuvantul e pe val acum si cuprinde cumva tot domeniul IT fara sa o spuna direct. Chiar daca avea conotatii negative in trecut, acum a devenit:  the new cool. Eu cred ca poate e un pic curajos, dar doar atat cat sa fiti memorabili, si ceea ce e misto e ca nici nu trebuie sa purtati vreo uniforma, trebuie doar sa fiti voi :)). 

In functie de numele ales de voi o sa incepem sa schitam si partea vizuala. 

May the force be with you!

**Comment by chousensha** [comment]
Mai adaug si eu o varianta:

MadHatConsulting

Ma mai gandesc si la altele, dar la mine dureaza asta ca daca stau la un joc cu orele sa ma gandesc la numele caracterului, sigur ca asta o sa fie si mai si =))

**Comment by opricescu** [comment]
Mertia asteptarea! Imi plac sugestiile tale!
